[package]
name = "pid-img-web-loader"
version = "0.1.0"
edition = "2021"

[build]
target = "wasm32-unknown-unknown"

[dependencies]
wasm-bindgen = "0.2.84"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
panic = "abort"
